
services:
  Backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.apache
    image: backend_laravel:latest
    container_name: backend_laravel
    hostname: Backend_Laravel
    volumes:
      - ./backend:/var/www/html
    ports:
      - 8000:80
    restart: always
    environment:
      - TZ=America/Sao_Paulo
    networks:
      - linklei-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  Frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend_react:latest
    container_name: frontend_react
    hostname: Frontend_React
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 5173:5173
    restart: always
    environment:
      - TZ=America/Sao_Paulo
      - NODE_ENV=development
    networks:
      - linklei-network
    stdin_open: true
    tty: true

networks:
  linklei-network:
    driver: bridge
